version: 2.1

orbs:
  php: circleci/php@1

jobs:
  test-php:
    docker:
      - image: cimg/php:8.1-node  # PHP 8.1に更新
    working_directory: ~/laravelgram  # 正しいディレクトリに修正
    
   
steps:
      - checkout
      - php/install-packages
      - run:
          name: Install Composer Dependencies
          
         
command: composer install
      
  
- run:
          
  
name: Run Laravel Tests
          command: php artisan test  # Laravelのテストコマンドに修正

  

 
deploy:
    
   
docker:
      - image: cimg/php:8.1-node  # PHP 8.1に合わせる
    steps:
      - add_ssh_keys:
          fingerprints:
            - "<CircleCIに追加したSSHキーのフィンガープリント>"
      
     
- run:
          name: Deploy to Production Server
          command: |
            scp -r ./* user@your-server.com:/path/to/deploy/
            ssh user@your-server.com 'cd /path/to/deploy && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && sudo service php-fpm reload'

workflows:
  build-and-test:
    jobs:
      - test-php
      - deploy:
          requires:
            
   
- test-php